/**
 * build-vercel.mjs
 *
 * Post-build script that converts the Vite output (dist/client + dist/server)
 * into Vercel's Output API format (.vercel/output/).
 *
 * Structure produced:
 *   .vercel/output/
 *     config.json          — routing rules (version 3)
 *     static/              — copy of dist/client/ (served as static files)
 *     functions/
 *       ssr.func/
 *         .vc-config.json  — Node.js function config
 *         index.js         — esbuild bundle: server + Node.js HTTP adapter
 */

import { execSync } from "node:child_process";
import {
  mkdirSync,
  cpSync,
  writeFileSync,
  rmSync,
  existsSync,
  writeFileSync as write,
} from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";
import { mkdtempSync } from "node:fs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

// ─── Step 1: Vite build ─────────────────────────────────────────────────────
console.log("→ Running Vite build…");
execSync("npm run build", { cwd: root, stdio: "inherit" });
console.log("✓ Vite build complete\n");

// ─── Step 2: Prepare .vercel/output ─────────────────────────────────────────
const outDir = resolve(root, ".vercel/output");
if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
mkdirSync(resolve(outDir, "static"), { recursive: true });
mkdirSync(resolve(outDir, "functions/ssr.func"), { recursive: true });

// ─── Step 2a: Static files ───────────────────────────────────────────────────
console.log("→ Copying static assets…");
cpSync(resolve(root, "dist/client"), resolve(outDir, "static"), {
  recursive: true,
});
console.log("✓ Static assets copied\n");

// ─── Step 2b: Bundle SSR function ────────────────────────────────────────────
console.log("→ Bundling SSR function…");

const serverEntry = resolve(root, "dist/server/server.js")
  .replace(/\\/g, "/");

// Write a temporary entry that wraps the fetch-style handler in a
// Node.js (req, res) adapter compatible with Vercel's Node.js runtime.
const tmpDir = mkdtempSync(resolve(tmpdir(), "vercel-ssr-"));
const entryFile = resolve(tmpDir, "entry.mjs");

writeFileSync(
  entryFile,
  /* js */ `
import server from ${JSON.stringify(serverEntry)};

/**
 * Convert a Node.js IncomingMessage to a Web Request.
 */
async function toWebRequest(req) {
  const proto =
    req.headers["x-forwarded-proto"] || "https";
  const host =
    req.headers["x-forwarded-host"] ||
    req.headers["host"] ||
    "localhost";
  const url = new URL(req.url || "/", proto + "://" + host);

  // Collect body chunks
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const hasBody =
    chunks.length > 0 &&
    !["GET", "HEAD"].includes((req.method || "GET").toUpperCase());

  // Build headers (Headers API)
  const headers = new Headers();
  for (const [k, v] of Object.entries(req.headers)) {
    if (v == null) continue;
    if (Array.isArray(v)) v.forEach((val) => headers.append(k, val));
    else headers.set(k, String(v));
  }

  return new Request(url.toString(), {
    method: req.method || "GET",
    headers,
    body: hasBody ? Buffer.concat(chunks) : undefined,
    // Required for Node.js 18+ when body is a stream/buffer
    duplex: "half",
  });
}

/**
 * Vercel Node.js serverless handler.
 */
export default async function handler(req, res) {
  try {
    const request = await toWebRequest(req);
    const response = await server.fetch(request, {}, {});

    res.statusCode = response.status;

    response.headers.forEach((value, key) => {
      const lower = key.toLowerCase();
      if (lower === "set-cookie") {
        // Preserve multiple Set-Cookie headers
        const existing = res.getHeader("set-cookie");
        res.setHeader(
          "set-cookie",
          existing ? [].concat(existing, value) : [value]
        );
      } else {
        res.setHeader(key, value);
      }
    });

    const buffer = Buffer.from(await response.arrayBuffer());
    res.end(buffer);
  } catch (err) {
    console.error("[SSR]", err);
    if (!res.headersSent) {
      res.statusCode = 500;
      res.end("Internal Server Error");
    }
  }
}
`.trim()
);

// Bundle with esbuild — produces a single self-contained CJS file
const { build } = await import("esbuild");

await build({
  entryPoints: [entryFile],
  bundle: true,
  platform: "node",
  target: "node22",
  // CJS avoids code-splitting and is simpler for Vercel Node.js runtime
  format: "cjs",
  outfile: resolve(outDir, "functions/ssr.func/index.js"),
  // Let esbuild bundle everything (no externals) so the func is self-contained
  external: [],
  minify: false,
  sourcemap: false,
  banner: {
    js: "// Auto-generated by scripts/build-vercel.mjs — do not edit",
  },
  // Needed because some deps use __dirname / require
  define: {
    "import.meta.url": JSON.stringify("file:///vercel/path0/index.js"),
  },
});

console.log("✓ SSR function bundled\n");

// ─── Step 2c: Function package.json (force CJS resolution) ──────────────────
// The project root has "type": "module", so we explicitly set commonjs
// in the function directory so Node.js treats index.js as CJS.
write(
  resolve(outDir, "functions/ssr.func/package.json"),
  JSON.stringify({ type: "commonjs" }, null, 2)
);

// ─── Step 2d: Function config (.vc-config.json) ──────────────────────────────
write(
  resolve(outDir, "functions/ssr.func/.vc-config.json"),
  JSON.stringify(
    {
      runtime: "nodejs22.x",
      handler: "index.js",
      launcherType: "Nodejs",
      maxDuration: 30,
    },
    null,
    2
  )
);

// ─── Step 3: Vercel routing config ───────────────────────────────────────────
write(
  resolve(outDir, "config.json"),
  JSON.stringify(
    {
      version: 3,
      routes: [
        // Cache hashed assets forever
        {
          src: "/assets/(.+)",
          headers: { "Cache-Control": "public, max-age=31536000, immutable" },
          continue: true,
        },
        // Serve anything that exists on disk as a static file
        { handle: "filesystem" },
        // Everything else → SSR function
        { src: "/(.*)", dest: "/ssr" },
      ],
    },
    null,
    2
  )
);

console.log("✓ .vercel/output ready");
console.log(`   static/          ← dist/client/`);
console.log(`   functions/ssr/   ← SSR Node.js function`);
console.log(`   config.json      ← routing rules`);
